site_name: Linking Boy
site_url: https://www.pixelrespawn.com
theme:
  name: material
  logo: images/linkboy-icon.png
  palette:
    primary: custom

copyright: Copyright &copy; 2024 Pixel Respawn LLC

extra_css:
  - stylesheets/extra.css
